# Generated by Django 3.0.5 on 2020-12-26 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getinfo',
            old_name='PortalOneSessionKey',
            new_name='portalOneSessionKey',
        ),
        migrations.RenameField(
            model_name='getinfo',
            old_name='ResponseCode',
            new_name='responseCode',
        ),
        migrations.RenameField(
            model_name='getinfo',
            old_name='ResponseMessage',
            new_name='responseMessage',
        ),
    ]
