# Generated by Django 3.0.5 on 2020-12-26 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_auto_20201226_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getinfo',
            old_name='portalOneSessionKey',
            new_name='PortalOneSessionKey',
        ),
    ]
