# Generated by Django 3.0.5 on 2020-12-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_auto_20201226_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getinfo',
            old_name='PortalOneSessionKey',
            new_name='portalOneSessionKey',
        ),
    ]
