# Generated by Django 3.0.5 on 2020-12-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResponseCode', models.CharField(default='', max_length=100)),
                ('PortalOneSessionKey', models.CharField(max_length=100)),
                ('ResponseMessage', models.CharField(max_length=100)),
                ('ExternalCustomerId', models.CharField(max_length=100)),
                ('CustomerName', models.CharField(max_length=100)),
            ],
        ),
    ]
