# Generated by Django 3.0.5 on 2020-12-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneinc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='getinfo',
            name='CustomerId',
            field=models.CharField(default='', max_length=100),
        ),
    ]
