# Generated by Django 3.0.5 on 2020-12-23 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneinc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getinfo',
            old_name='authentication',
            new_name='portalOneSessionKey',
        ),
        migrations.RenameField(
            model_name='getinfo',
            old_name='token',
            new_name='responseCode',
        ),
    ]
