# Generated by Django 3.0.5 on 2020-12-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneinc', '0003_auto_20201227_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getinfo',
            name='CustomerId',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='getinfo',
            name='CustomerName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='getinfo',
            name='ExternalCustomerId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='getinfo',
            name='PortalOneSessionKey',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='getinfo',
            name='ResponseCode',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='getinfo',
            name='ResponseMessage',
            field=models.CharField(max_length=100),
        ),
    ]
