# Generated by Django 3.0.5 on 2020-12-25 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneinc', '0003_auto_20201225_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getinfo',
            old_name='portalOneSessionKey',
            new_name='PortalOneSessionKey',
        ),
        migrations.RenameField(
            model_name='getinfo',
            old_name='responseMessage',
            new_name='ResponseMessage',
        ),
    ]
