# Generated by Django 3.0.5 on 2020-12-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneinc', '0005_auto_20201226_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getinfo',
            old_name='portalOneSessionKey',
            new_name='PortalOneSessionKey',
        ),
        migrations.RenameField(
            model_name='getinfo',
            old_name='responseCode',
            new_name='ResponseCode',
        ),
        migrations.RenameField(
            model_name='getinfo',
            old_name='responseMessage',
            new_name='ResponseMessage',
        ),
    ]
