# Generated by Django 3.0.5 on 2020-12-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneinc', '0005_auto_20201227_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getinfo',
            name='PortalOneSessionKey',
            field=models.CharField(max_length=100),
        ),
    ]
